In [1]:
import pandas as pd
import numpy as np

In [ ]:
#Load the file students.csv and make sure Score Date is parsed as datetime.
df = pd.read_csv('students.csv', parse_dates=['Score Date'])
df

   Student ID     Name  Age  Grade    Subject        City  Passed Score Date
0           1    Ahmed   25   88.0       Math       Cairo    True 2025-01-15
1           2     Sara   32   92.0    Physics  Alexandria    True 2025-02-10
2           3     Omar   19   65.0       Math        Giza   False 2025-01-20
3           4     Lina   28   78.0  Chemistry       Cairo    True 2025-03-05
4           5   Khaled   45   55.0    Physics    Mansoura   False 2025-02-28
5           6     Nour   22    NaN    English  Alexandria    True 2025-01-10
6           7     Yara   30   89.0       Math       Cairo    True        NaT
7           8  Mohamed   27   72.0  Chemistry        Giza    True 2025-03-12
8           8  Mohamed   27   72.0  Chemistry        Giza    True 2025-03-12

In [9]:
#Print the shape, columns list, and data types of the DataFrame.
print("Shape is:", df.shape, "\n")
print("Columns are:", df.columns, "\n")
print("Data types are:","\n", df.info())

Shape is: (9, 8)

Columns are: Index(['Student ID', 'Name', 'Age', 'Grade', 'Subject', 'City', 'Passed',
       'Score Date'],
      dtype='object')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student ID  9 non-null      int64
 1   Name        9 non-null      object
 2   Age         9 non-null      int64
 3   Grade       8 non-null      float64
 4   Subject     9 non-null      object
 5   City        9 non-null      object
 6   Passed      9 non-null      bool
 7   Score Date  8 non-null      datetime64[ns]
dtypes: bool(1), datetime64[ns](1), float64(1), int64(2), object(3)
memory usage: 645.0+ bytes
Data types are:
 None

In [7]:
#Show the first 7 rows and the last 3 rows.
print("First 7 rows:\n", df.head(7), "\n")
print("Last 3 rows:\n", df.tail(3))

First 7 rows:
    Student ID    Name  Age  Grade    Subject        City  Passed Score Date
0           1   Ahmed   25   88.0       Math       Cairo    True 2025-01-15
1           2    Sara   32   92.0    Physics  Alexandria    True 2025-02-10
2           3    Omar   19   65.0       Math        Giza   False 2025-01-20
3           4    Lina   28   78.0  Chemistry       Cairo    True 2025-03-05
4           5  Khaled   45   55.0    Physics    Mansoura   False 2025-02-28
5           6    Nour   22    NaN    English  Alexandria    True 2025-01-10
6           7    Yara   30   89.0       Math       Cairo    True        NaT

Last 3 rows:
    Student ID     Name  Age  Grade    Subject   City  Passed Score Date
6           7     Yara   30   89.0       Math  Cairo    True        NaT
7           8  Mohamed   27   72.0  Chemistry   Giza    True 2025-03-12
8           8  Mohamed   27   72.0  Chemistry   Giza    True 2025-03-12

In [10]:
#Show how many missing values in each column
df.isna().sum()

Student ID    0
Name          0
Age           0
Grade         1
Subject       0
City          0
Passed        0
Score Date    1
dtype: int64

In [11]:
#What is the average, minimum, and maximum Grade?
print("Average:", df['Grade'].mean())
print("Minimum:", df['Grade'].min())
print("Maximum:", df['Grade'].max())

Average: 76.375
Minimum: 55.0
Maximum: 92.0

In [13]:
# How many unique cities are there? List them.
unique_cities = df['City'].unique()
print("Number of unique cities:", len(unique_cities))
print("Unique cities:", unique_cities)

Number of unique cities: 4
Unique cities: ['Cairo' 'Alexandria' 'Giza' 'Mansoura']

In [15]:
#Use value_counts() to show how many students per Subject
df['Subject'].value_counts()

Subject
Math         3
Chemistry    3
Physics      2
English      1
Name: count, dtype: int64

In [16]:
#Select only the columns: Name, Grade, Subject, City.
selected_columns = df[['Name', 'Grade', 'Subject', 'City']]
selected_columns

      Name  Grade    Subject        City
0    Ahmed   88.0       Math       Cairo
1     Sara   92.0    Physics  Alexandria
2     Omar   65.0       Math        Giza
3     Lina   78.0  Chemistry       Cairo
4   Khaled   55.0    Physics    Mansoura
5     Nour    NaN    English  Alexandria
6     Yara   89.0       Math       Cairo
7  Mohamed   72.0  Chemistry        Giza
8  Mohamed   72.0  Chemistry        Giza

In [17]:
#Show all students who Passed and have Grade ≥ 85.
df[(df['Passed'] == True) & (df['Grade'] >= 85)]

   Student ID   Name  Age  Grade  Subject        City  Passed Score Date
0           1  Ahmed   25   88.0     Math       Cairo    True 2025-01-15
1           2   Sara   32   92.0  Physics  Alexandria    True 2025-02-10
6           7   Yara   30   89.0     Math       Cairo    True        NaT

In [19]:
#Show students whose Name contains the letter "a" or "A" (case insensitive).
df[df['Name'].str.contains('a', case=False)]

   Student ID     Name  Age  Grade    Subject        City  Passed Score Date
0           1    Ahmed   25   88.0       Math       Cairo    True 2025-01-15
1           2     Sara   32   92.0    Physics  Alexandria    True 2025-02-10
2           3     Omar   19   65.0       Math        Giza   False 2025-01-20
3           4     Lina   28   78.0  Chemistry       Cairo    True 2025-03-05
4           5   Khaled   45   55.0    Physics    Mansoura   False 2025-02-28
6           7     Yara   30   89.0       Math       Cairo    True        NaT
7           8  Mohamed   27   72.0  Chemistry        Giza    True 2025-03-12
8           8  Mohamed   27   72.0  Chemistry        Giza    True 2025-03-12

In [22]:
#Show students in Cairo or Alexandria with Grade < 80.
df[(df['City'] == 'Cairo') | (df['City'] == 'Alexandria') & (df['Grade'] < 80)]

   Student ID   Name  Age  Grade    Subject   City  Passed Score Date
0           1  Ahmed   25   88.0       Math  Cairo    True 2025-01-15
3           4   Lina   28   78.0  Chemistry  Cairo    True 2025-03-05
6           7   Yara   30   89.0       Math  Cairo    True        NaT

In [24]:
#Show students with Grade between 80 and 90 (inclusive).
df[(df['Grade'] >= 80) & (df['Grade'] <= 90)]

   Student ID   Name  Age  Grade Subject   City  Passed Score Date
0           1  Ahmed   25   88.0    Math  Cairo    True 2025-01-15
6           7   Yara   30   89.0    Math  Cairo    True        NaT

In [27]:
#Using .loc, change Khaled's grade from 55 to 68
df.loc[df['Name'] == 'Khaled', 'Grade'] = 68

df[df['Name'] == 'Khaled']

   Student ID    Name  Age  Grade  Subject      City  Passed Score Date
4           5  Khaled   45   68.0  Physics  Mansoura   False 2025-02-28

In [30]:
#Add a new column Is_Excellent that is True if Grade ≥ 90, False otherwise (vectorized).
df['Is_Excellent'] = df['Grade'] >= 90
df

,Student ID,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent
0,1,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False
1,2,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,True
2,3,Omar,19,65.0,Math,Giza,False,2025-01-20,False
3,4,Lina,28,78.0,Chemistry,Cairo,True,2025-03-05,False
4,5,Khaled,45,68.0,Physics,Mansoura,False,2025-02-28,False
5,6,Nour,22,NaN,English,Alexandria,True,2025-01-10,False
6,7,Yara,30,89.0,Math,Cairo,True,NaT,False
7,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False
8,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False

In [31]:
#Fill missing Grade values with the average Grade.
average_grade = df['Grade'].mean()
df['Grade'].fillna(average_grade, inplace=True)
df

,Student ID,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent
0,1,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False
1,2,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,True
2,3,Omar,19,65.0,Math,Giza,False,2025-01-20,False
3,4,Lina,28,78.0,Chemistry,Cairo,True,2025-03-05,False
4,5,Khaled,45,68.0,Physics,Mansoura,False,2025-02-28,False
5,6,Nour,22,78.0,English,Alexandria,True,2025-01-10,False
6,7,Yara,30,89.0,Math,Cairo,True,NaT,False
7,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False
8,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False

In [33]:
#Fill missing Score Date values with the most common date (mode)
date = df['Score Date'].mode()[0]
df['Score Date'].fillna(date, inplace=True)
df

,Student ID,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent
0,1,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False
1,2,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,True
2,3,Omar,19,65.0,Math,Giza,False,2025-01-20,False
3,4,Lina,28,78.0,Chemistry,Cairo,True,2025-03-05,False
4,5,Khaled,45,68.0,Physics,Mansoura,False,2025-02-28,False
5,6,Nour,22,78.0,English,Alexandria,True,2025-01-10,False
6,7,Yara,30,89.0,Math,Cairo,True,2025-03-12,False
7,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False
8,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False

In [34]:
#Add a new column Final_Grade = Grade + 5 (bonus points).
df['Final_Grade'] = df['Grade'] + 5
df

,Student ID,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade
0,1,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False,93.0
1,2,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,True,97.0
2,3,Omar,19,65.0,Math,Giza,False,2025-01-20,False,70.0
3,4,Lina,28,78.0,Chemistry,Cairo,True,2025-03-05,False,83.0
4,5,Khaled,45,68.0,Physics,Mansoura,False,2025-02-28,False,73.0
5,6,Nour,22,78.0,English,Alexandria,True,2025-01-10,False,83.0
6,7,Yara,30,89.0,Math,Cairo,True,2025-03-12,False,94.0
7,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0
8,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0

In [ ]:
# •Create a column Grade_Category using pd.cut with bins:
# •0–69 → "Fail"
# •70–79 → "Average"
# •80–89 → "Good"
# •90–100 → "Excellent"

In [35]:
df['Grade_Category'] = pd.cut(df['Grade'], bins=[0, 69, 79, 89, 100], labels=["Fail", "Average", "Good", "Excellent"])
df

,Student ID,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category
0,1,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False,93.0,Good
1,2,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,True,97.0,Excellent
2,3,Omar,19,65.0,Math,Giza,False,2025-01-20,False,70.0,Fail
3,4,Lina,28,78.0,Chemistry,Cairo,True,2025-03-05,False,83.0,Average
4,5,Khaled,45,68.0,Physics,Mansoura,False,2025-02-28,False,73.0,Fail
5,6,Nour,22,78.0,English,Alexandria,True,2025-01-10,False,83.0,Average
6,7,Yara,30,89.0,Math,Cairo,True,2025-03-12,False,94.0,Good
7,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average
8,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average

In [36]:
#Remove the column Student ID.
df.drop(columns= 'Student ID')
df

,Student ID,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category
0,1,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False,93.0,Good
1,2,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,True,97.0,Excellent
2,3,Omar,19,65.0,Math,Giza,False,2025-01-20,False,70.0,Fail
3,4,Lina,28,78.0,Chemistry,Cairo,True,2025-03-05,False,83.0,Average
4,5,Khaled,45,68.0,Physics,Mansoura,False,2025-02-28,False,73.0,Fail
5,6,Nour,22,78.0,English,Alexandria,True,2025-01-10,False,83.0,Average
6,7,Yara,30,89.0,Math,Cairo,True,2025-03-12,False,94.0,Good
7,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average
8,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average

In [37]:
#Keep only students who Passed.
passed_students = df[df['Passed'] == True]
passed_students

,Student ID,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category
0,1,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False,93.0,Good
1,2,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,True,97.0,Excellent
3,4,Lina,28,78.0,Chemistry,Cairo,True,2025-03-05,False,83.0,Average
5,6,Nour,22,78.0,English,Alexandria,True,2025-01-10,False,83.0,Average
6,7,Yara,30,89.0,Math,Cairo,True,2025-03-12,False,94.0,Good
7,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average
8,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average

In [38]:
#Sort the DataFrame by Grade descending.
sorted_df = df.sort_values(by='Grade', ascending=False)
sorted_df

,Student ID,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category
1,2,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,True,97.0,Excellent
6,7,Yara,30,89.0,Math,Cairo,True,2025-03-12,False,94.0,Good
0,1,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False,93.0,Good
3,4,Lina,28,78.0,Chemistry,Cairo,True,2025-03-05,False,83.0,Average
5,6,Nour,22,78.0,English,Alexandria,True,2025-01-10,False,83.0,Average
7,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average
8,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average
4,5,Khaled,45,68.0,Physics,Mansoura,False,2025-02-28,False,73.0,Fail
2,3,Omar,19,65.0,Math,Giza,False,2025-01-20,False,70.0,Fail

In [39]:
#Sort by City ascending, then inside each city sort by Grade descending.
sorted = df.sort_values(by=['City', 'Grade'], ascending=[True, False])
sorted

,Student ID,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category
1,2,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,True,97.0,Excellent
5,6,Nour,22,78.0,English,Alexandria,True,2025-01-10,False,83.0,Average
6,7,Yara,30,89.0,Math,Cairo,True,2025-03-12,False,94.0,Good
0,1,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False,93.0,Good
3,4,Lina,28,78.0,Chemistry,Cairo,True,2025-03-05,False,83.0,Average
7,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average
8,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average
2,3,Omar,19,65.0,Math,Giza,False,2025-01-20,False,70.0,Fail
4,5,Khaled,45,68.0,Physics,Mansoura,False,2025-02-28,False,73.0,Fail

In [40]:
#Add a column Rank that ranks students by Grade (1 = highest, handle ties with 'min').
df['Rank'] = df['Grade'].rank(method='min', ascending=False)
df

,Student ID,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category,Rank
0,1,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False,93.0,Good,3.0
1,2,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,True,97.0,Excellent,1.0
2,3,Omar,19,65.0,Math,Giza,False,2025-01-20,False,70.0,Fail,9.0
3,4,Lina,28,78.0,Chemistry,Cairo,True,2025-03-05,False,83.0,Average,4.0
4,5,Khaled,45,68.0,Physics,Mansoura,False,2025-02-28,False,73.0,Fail,8.0
5,6,Nour,22,78.0,English,Alexandria,True,2025-01-10,False,83.0,Average,4.0
6,7,Yara,30,89.0,Math,Cairo,True,2025-03-12,False,94.0,Good,2.0
7,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average,6.0
8,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average,6.0

In [41]:
#Show the top 4 students with the highest grades (use nlargest).
df.nlargest(4, 'Grade')

,Student ID,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category,Rank
1,2,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,True,97.0,Excellent,1.0
6,7,Yara,30,89.0,Math,Cairo,True,2025-03-12,False,94.0,Good,2.0
0,1,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False,93.0,Good,3.0
3,4,Lina,28,78.0,Chemistry,Cairo,True,2025-03-05,False,83.0,Average,4.0

In [42]:
#Show the 3 youngest students.
df.nsmallest(columns='Age', n=3)

,Student ID,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category,Rank
2,3,Omar,19,65.0,Math,Giza,False,2025-01-20,False,70.0,Fail,9.0
5,6,Nour,22,78.0,English,Alexandria,True,2025-01-10,False,83.0,Average,4.0
0,1,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False,93.0,Good,3.0

In [43]:
# Find the student(s) with the highest Grade and show their Name and Grade.
highest_grade = df['Grade'].max()
df[df['Grade'] == highest_grade][['Name', 'Grade']]

   Name  Grade
1  Sara   92.0

In [44]:
# After filling missing grades, recalculate the average Grade per Subject.
df.groupby('Subject')['Grade'].mean()

Subject
Chemistry    74.000000
English      78.000000
Math         80.666667
Physics      80.000000
Name: Grade, dtype: float64

In [46]:
#Create a new column City_Avg that shows the average grade of each student's city (using transform).
df['City_Avg'] = df.groupby('City')['Grade'].transform('mean')
df

,Student ID,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category,Rank,City_Avg
0,1,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False,93.0,Good,3.0,85.000000
1,2,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,True,97.0,Excellent,1.0,85.000000
2,3,Omar,19,65.0,Math,Giza,False,2025-01-20,False,70.0,Fail,9.0,69.666667
3,4,Lina,28,78.0,Chemistry,Cairo,True,2025-03-05,False,83.0,Average,4.0,85.000000
4,5,Khaled,45,68.0,Physics,Mansoura,False,2025-02-28,False,73.0,Fail,8.0,68.000000
5,6,Nour,22,78.0,English,Alexandria,True,2025-01-10,False,83.0,Average,4.0,85.000000
6,7,Yara,30,89.0,Math,Cairo,True,2025-03-12,False,94.0,Good,2.0,85.000000
7,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average,6.0,69.666667
8,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average,6.0,69.666667

In [47]:
# Show the subject with the highest average grade.
subject_avg = df.groupby('Subject')['Grade'].mean()
highest_subject = subject_avg.idxmax()
print("highest subject:", highest_subject)

highest subject: Math